# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSInter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSInter
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI'
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Auth'

  target 'iOSInterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSInterUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
